name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: stable

      - run: flutter clean
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter packages pub get
      - run: find web
      - run: flutter build web

      - name: deploy to pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/web  # The folder the action should deploy.
